//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSNWebApp.LaunchVehicleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LaunchVehicleService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromDSN", ReplyAction="http://tempuri.org/IService1/receiveCommandFromDSNResponse")]
        void receiveCommandFromDSN(int launchVehicleId, int orbit, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromDSN", ReplyAction="http://tempuri.org/IService1/receiveCommandFromDSNResponse")]
        System.Threading.Tasks.Task receiveCommandFromDSNAsync(int launchVehicleId, int orbit, string command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DSNWebApp.LaunchVehicleService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DSNWebApp.LaunchVehicleService.IService1>, DSNWebApp.LaunchVehicleService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void receiveCommandFromDSN(int launchVehicleId, int orbit, string command) {
            base.Channel.receiveCommandFromDSN(launchVehicleId, orbit, command);
        }
        
        public System.Threading.Tasks.Task receiveCommandFromDSNAsync(int launchVehicleId, int orbit, string command) {
            return base.Channel.receiveCommandFromDSNAsync(launchVehicleId, orbit, command);
        }
    }
}
