//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchVehicleService.PayloadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PayloadService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromDSN", ReplyAction="http://tempuri.org/IService1/receiveCommandFromDSNResponse")]
        string receiveCommandFromDSN(int payloadId, string type, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromDSN", ReplyAction="http://tempuri.org/IService1/receiveCommandFromDSNResponse")]
        System.Threading.Tasks.Task<string> receiveCommandFromDSNAsync(int payloadId, string type, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromLaunchVehicle", ReplyAction="http://tempuri.org/IService1/receiveCommandFromLaunchVehicleResponse")]
        void receiveCommandFromLaunchVehicle(int payloadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveCommandFromLaunchVehicle", ReplyAction="http://tempuri.org/IService1/receiveCommandFromLaunchVehicleResponse")]
        System.Threading.Tasks.Task receiveCommandFromLaunchVehicleAsync(int payloadId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LaunchVehicleService.PayloadService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LaunchVehicleService.PayloadService.IService1>, LaunchVehicleService.PayloadService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string receiveCommandFromDSN(int payloadId, string type, string command) {
            return base.Channel.receiveCommandFromDSN(payloadId, type, command);
        }
        
        public System.Threading.Tasks.Task<string> receiveCommandFromDSNAsync(int payloadId, string type, string command) {
            return base.Channel.receiveCommandFromDSNAsync(payloadId, type, command);
        }
        
        public void receiveCommandFromLaunchVehicle(int payloadId) {
            base.Channel.receiveCommandFromLaunchVehicle(payloadId);
        }
        
        public System.Threading.Tasks.Task receiveCommandFromLaunchVehicleAsync(int payloadId) {
            return base.Channel.receiveCommandFromLaunchVehicleAsync(payloadId);
        }
    }
}
